cart/urls.py
from django.urls import path
from . import views
from cart import views


urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/increase_quantity/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import user_login, user_signup
from products import views as product_views
from cart import views as cart_views
from orders import views as order_views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from authentication.views import user_signup
from authentication.views import user_signup, user_login, user_logout
from django.conf import settings
from django.conf.urls.static import static
from products import views





urlpatterns = [
    path('', TemplateView.as_view(template_name='homepage/homepage.html'), name='homepage'),
    path('signup/', user_signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('cart/remove/<int:item_id>/', cart_views.remove_from_cart, name='remove_from_cart'),
    path('products/', product_views.product_list, name='product_list'),
    path('products/<int:product_id>/', product_views.product_detail, name='product_detail'),
    path('products/categories/<int:category_id>/', views.category_detail, name='category_detail'),
    path('products/add_to_cart/<int:product_id>/', cart_views.add_to_cart, name='add_to_cart'),
    path('cart/', cart_views.view_cart, name='view_cart'),
    path('place_order/', order_views.place_order, name='place_order'),
    path('admin/', admin.site.urls),
    path('cart/increase_quantity/<int:item_id>/', cart_views.increase_quantity, name='increase_quantity'),
    path('search-product/', views.search_product, name='search_product'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from . import views
from . import add_to_cart

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('products/', views.product_list, name='product_list'),
    path('cart/', views.view_cart, name='view_cart'),
    path('categories/<int:category_id>/', views.category_detail, name='category_detail'),
    path('search-product/', views.search_product, name='search_product'),
]

products/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_photos')


    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from cart.models import Cart
from .models import Category
from django.http import JsonResponse
from django.urls import reverse

def product_list(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        'products': products
    }
    return render(request, 'products/product_list.html', context)

def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    context = {'product': product}
    return render(request, 'products/product_detail.html', context)


def category_detail(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'products': products
    }

    return render(request, 'products/category_detail.html', context)


def view_cart(request):
    user = request.user
    try:
        cart = Cart.objects.get(user=user)
    except Cart.DoesNotExist:
        cart = None
    context = {'cart': cart}
    return render(request, 'cart/view_cart.html', context)


def search_product(request):
    search_term = request.GET.get('search')

    try:
        product = Product.objects.get(name__icontains=search_term)
        product_detail_url = reverse('product_detail', args=[product.id])
        return JsonResponse({'productDetailURL': product_detail_url})
    except Product.DoesNotExist:
        return JsonResponse({'productDetailURL': None})

products/templates/products/category_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Dettagli Categoria</title>
    <link rel="stylesheet" type="text/css" href="{% static 'category.css' %}">
    <style>
body {
  background-color: #cfe8cf;
  font-family: sans-serif;
}

h1 {
  text-align: center;
  font-size: 60px;
  color: #000;
}

.product-container {
  display: flex;
  padding: 0;
  margin: 10px 0;
  flex-wrap: wrap;
  overflow-x: auto;
  justify-content: center;
}

.product-container li {
  flex: 0 0 auto;
  margin: 10px;
  padding: 10px;
  border: 2px solid #000;
  border-radius: 5px;
  text-align: center;
  min-width: 200px;
  left: 2%;
  position: relative;
}

.product-container h3 {
  font-size: 24px;
  font-family: fantasy;
  font-weight: bold;
  margin: 0;
}

.product-container .price {
  font-weight: bold;
  font-size: 20px;
  margin-top: 10px;
  text-align: center;
}

.product-container a {
  display: inline-block;
  margin-top: 10px;
  margin-right: 10px;
  padding: 8px 16px;
  border-radius: 4px;
  color: white;
  background-color: #4caf50;
  text-decoration: none;
  font-size: 20px;
  margin-left: 10px;
  transition: background-color 0.3s, color 0.3s, border-color 0.3s;
  border: 2px solid white;
  border-color: #4caf50;
  box-sizing: border-box;
}

.product-container a:hover {
  background-color: #cfe8cf;
  color: #4caf50;
  border-color: #4caf50;
}

ul {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.product-container .product-box {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
}

.product-container .product-image {
  margin-bottom: 10px;
  max-width: 100px;
  max-height: 100px;
  object-fit: cover;
  border-radius: 10px;
  transition: 0.6s ease;
}

.product-image:hover {
  transform: scale(1.07);
}

a#prodotti_link {
  margin-top: 0px;
  text-decoration: none;
  font-size: 0px;
  color: none;
  background-color: #cfe8cf !important;
  padding: 0px 0px;
  border-radius: 4px;
  margin-left: 0px;
  border: 0px solid white;
}

a#prodotti_link:hover {
  background-color: none !important;
  color: none !important;
  border-color: none !important;
}

a.view_all {
  position: relative;
  top: -10px;
  text-decoration: none;
  font-size: 20px;
  color: white;
  background-color: #4caf50;
  padding: 8px 16px;
  border-radius: 4px;
  margin-left: 10px;
  transition: background-color 0.3s, color 0.3s, border-color 0.3s;
  border: 2px solid white;
  border-color: #4caf50;
  box-sizing: border-box;
}

a.view_all:hover {
  background-color: #cfe8cf !important;
  color: #4caf50;
  border-color: #4caf50;
}

@media (max-width: 768px) {
  h1 {
    font-size: 40px;
  }
}
</style>

</head>
<body>
        <h1>{{ category.name }}
        <a class="view_all" href="{% url 'product_list' %}">Torna ai prodotti</a></h1>

    <ul class="product-container">
        {% for product in category.product_set.all %}
                        <li>
                            <div class="product-box">
                                <div class="product-image">
                                        <a id="prodotti_link" href="{% url 'product_detail' product.id %}"><img class="product-image" src="{{ product.image.url }}" alt="Product Image"> </a>


                                </div>
                                <h3>{{ product.name }}</h3>
                                <p class="price">Prezzo: {{ product.price }} €</p>
                                <a href="{% url 'product_detail' product.id %}">Dettagli</a>
                            </div>
                        </li>
                {% empty %}
                        <li>Nessun prodotto disponibile.</li>
            </ul>
        {% endfor %}
    </div>
</body>
</html>

products/templates/products/product_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Dettaglio Prodotto</title>
    <link rel="stylesheet" type="text/css" href="{% static 'product_detail.css' %}">
    <style>
        #canvas-container {
            width: 500px;
            height: 300px;
            position: relative;
            overflow: hidden;
            border-radius: 10px;
        }

        #canvas {
            width: 100%;
            height: 100%;
        }

        .product-image {
            width: 500px;
            height: 300px;
            object-fit: cover;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        {% if product.category.name == "Scarpe" %}
            <div id="canvas-container">
                <script type="module" src="https://unpkg.com/@splinetool/viewer/build/spline-viewer.js"></script>
                <spline-viewer url="https://prod.spline.design/Dp8Yy6KwSBlF90iQ/scene.splinecode"></spline-viewer>
            </div>
        {% else %}
            <img class="product-image" src="{{ product.image.url }}" alt="Product Image">
        {% endif %}
        <h1>{{ product.name }}</h1>
        <p>{{ product.description }}</p>
        <p class="price">Prezzo: €{{ product.price }}</p>
        {% if user.is_authenticated %}
        <a href="{% url 'add_to_cart' product.id %}">Aggiungi al carrello</a>
        {% endif %}
        <a href="{% url 'product_list' %}">Torna alla lista dei prodotti</a>
    </div>
</body>
</html>